---
title: "Interactive Map of Tornado-Induced Property Damage"
author: "Jeremy Diaz"
date: "June 19, 2017"
output: html_document
---

### The Data

The data used for this visualization comes from the NOAA-provided Storm Events Database. The data is subsetted to only tornado events since Jan 1, 1997 with complete (no NA's) entries for property damage, beginning time & date, and beginning location.

### Map Details

The value which appears on the dark-grey cluster points is indicative of how many tornado events are being clustered into that point. Each dark-grey cluster point will decompose into individual tornado events upon zooming, which can be done by scrolling the mouse wheel, clicking the interactive buttons, or by clicking on the cluster point of interest. The more brightly-colored a tornado event point is, the more property damage it caused. Tornadoes which caused no property damage, in addition to being black, appear smaller than those which did.

If you hover your mouse over a tornado event point, a label will display the property damage caused by that event and the date when the damage occurred.

```{r interactive_map_plot, echo = FALSE, message = FALSE}



# Packages
library(leaflet)
library(viridis)
library(mapview)


# Import the data
tor_df <- read.csv("~/earth-analytics/tornadoesr/data/raw/leaflet_viz_data.csv")


# Make log-transformed property damage its own column
tor_df$LOG_DAM <- log(tor_df$DAMAGE_PROPERTY + 1,
                      base = exp(1))


# Get the date on each event (without time)
tor_df$BEGIN_DATE <- substring(tor_df$BEGIN_DATE_TIME, 1, 10)


# Get the color a palette
pal <- colorNumeric(palette = "inferno",
                    domain = tor_df$LOG_DAM)


# No scientific "e+6" notation
options("scipen" = 100)


# Make the interactive map
leaflet(tor_df,
        width = "100%",
        padding = 3,
        options = leafletOptions(minZoom = 4)) %>%
  addTiles() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addCircleMarkers(lng = tor_df$BEGIN_LON,
                   lat = tor_df$BEGIN_LAT, 
                   stroke = FALSE,
                   radius = ~ifelse(tor_df$DAMAGE_PROPERTY == 0, 8, 12),
                   fill = TRUE,
                   fillColor = ~pal(tor_df$LOG_DAM),
                   fillOpacity = 0.85,
                   labelOptions = labelOptions(textsize = "12px"),
                   label = ~paste(paste("Property Damages: ",
                                        paste0(paste0("$",
                                                      prettyNum(tor_df$DAMAGE_PROPERTY,
                                                                big.mark = ",",
                                                                scientific = FALSE)),
                                               ";")),
                                  paste("Date: ",
                                        tor_df$BEGIN_DATE),
                                  sep = "   "),
                   clusterOptions = markerClusterOptions(iconCreateFunction=JS("function (cluster) {    
    var childCount = cluster.getChildCount();  
    if (childCount < 100) {  
      c = 'rgba(115, 115, 115, 1.0);'
    } else if (childCount < 1000) {  
      c = 'rgba(115, 115, 115, 1);'  
    } else { 
      c = 'rgba(115, 115, 115, 1);'  
    }    
    return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', className: 'marker-cluster', iconSize: new L.Point(40, 40) });

  }")))



```


